server:
  port: 8080

spring:
  application:
    name: user-service
  cloud:
    config:
      import-check:
        enabled: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000


  datasource:
    url: jdbc:h2:mem:ms-user
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
