api-endereco:         # corresponde ao @FeignClient(name = "api-endereco")
   url: https://viacep.com.br/ws



spring:
  cloud:
    config:
      import-check:
        enabled: false









  datasource:
    url: jdbc:postgresql://localhost:5432/ms-user
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
